[tool.poetry]
name = "RitsukiBot"
version = "0.1.0"
description = "QQbot based on Nonebot"
authors = ["Soku_Ritsuki"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
openpyxl = "^3.0.7"
nonebot = {extras = ["scheduler"], version = "^1.8.4"}
requests = "^2.26.0"
feedparser = "^6.0.8"
ujson = "^4.1.0"
jieba = "^0.42.1"
beautifulsoup4 = "^4.10.0"
lxml = "^4.6.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
